memory_limit=256M
upload_max_filesize=32M
post_max_size=32M
max_execution_time=60

opcache.enable=1
opcache.enable_cli=1
opcache.validate_timestamps=0
opcache.memory_consumption=128
opcache.interned_strings_buffer=16
opcache.max_accelerated_files=20000
opcache.jit=off
